byte byteExample = 200;
short shortExample = 32_000;
int intExample = 2_147_400_500;
long longExample = -9_000_000_000_000_000_000;
sbyte sbyteExample = -100;
ushort ushortExample = 65_000;
uint uintExample = 4_000_000_000;
ulong ulongExample = 18_000_000_000_000_000_000;
float floatExample = 10.0F;
double doubleExample = 1234.1234543;
decimal decimalExample = 1234.12341234124M;
bool  boolExample = false;
string stringExample = "Landime";
char  charExample =  'a';

Console.WriteLine("Byte example: " + byteExample);
Console.WriteLine("Short example: " + shortExample);
Console.WriteLine("Int example: " + intExample);
Console.WriteLine("Long example: " + longExample);
Console.WriteLine("sByte example: " + sbyteExample);
Console.WriteLine("uShort example: " + ushortExample);
Console.WriteLine("uInt example: " + uintExample);
Console.WriteLine("uLong example: " + ulongExample);
Console.WriteLine("Float example: " + floatExample);
Console.WriteLine("Double example: " + doubleExample);
Console.WriteLine("Decimal example: " + decimalExample);
Console.WriteLine("Boolean example: " + boolExample);
Console.WriteLine("String example: " + stringExample);
Console.WriteLine("Char example: " + charExample);


byteExample = 250;
shortExample = 32_100;
intExample = 2_147_430_500;
longExample = -9_000_500_000_000_000_000;
sbyteExample = -90;
ushortExample = 65_100;
uintExample = 4_000_030_000;
ulongExample = 18_000_000_999_000_000_000;
floatExample = 10.34F;
doubleExample = 12342.1234543;
decimalExample = 1234.123412341241234M;
boolExample = true;
stringExample = "Vagabond";
charExample = '@';

Console.WriteLine("--------------------------------------------------");
Console.WriteLine("New Byte example: " + byteExample);
Console.WriteLine("New Short example: " + shortExample);
Console.WriteLine("New Int example: " + intExample);
Console.WriteLine("New Long example: " + longExample);
Console.WriteLine("New sByte example: " + sbyteExample);
Console.WriteLine("New uShort example: " + ushortExample);
Console.WriteLine("New uInt example: " + uintExample);
Console.WriteLine("New uLong example: " + ulongExample);
Console.WriteLine("New Float example: " + floatExample);
Console.WriteLine("New Double example: " + doubleExample);
Console.WriteLine("New Decimal example: " + decimalExample);
Console.WriteLine("New Boolean example: " + boolExample);
Console.WriteLine("New String example: " + stringExample);
Console.WriteLine("New Char example: " + charExample);